FROM debian
MAINTAINER Ronmi Ren <ronmi.ren@gmail.com>
RUN echo 'deb http://ftp.debian.org/debian jessie main'|tee '/etc/apt/sources.list.d/test.list'
RUN apt-get update
RUN apt-get install -y pkg1 && apt-get clean
RUN apt-get install -y pkg2 pkg3 && apt-get clean
